hidev asset-package/update bower jquery
hidev asset-package/update bower jquery.inputmask
hidev asset-package/update bower yii2-pjax
hidev asset-package/update bower punycode
hidev asset-package/update bower adminlte
hidev asset-package/update bower autosize
hidev asset-package/update bower bootstrap
hidev asset-package/update bower bootstrap-daterangepicker
hidev asset-package/update bower bootstrap-switch
hidev asset-package/update bower chartjs
hidev asset-package/update bower drmonty-datatables-plugins
hidev asset-package/update bower flag-icon-css
hidev asset-package/update bower icheck
hidev asset-package/update bower jquery-resizable-columns
hidev asset-package/update bower jquery-ui
hidev asset-package/update bower less-space
hidev asset-package/update bower lightbox2
hidev asset-package/update bower matchheight
hidev asset-package/update bower moment
hidev asset-package/update bower octicons
hidev asset-package/update bower paulzi-form
hidev asset-package/update bower pnotify
hidev asset-package/update bower select2
hidev asset-package/update bower store-js
hidev asset-package/update bower typeahead.js
hidev asset-package/update bower x-editable
