./vendor/bin/hidev asset-package/update bower jquery
./vendor/bin/hidev asset-package/update bower jquery.inputmask
./vendor/bin/hidev asset-package/update bower yii2-pjax
./vendor/bin/hidev asset-package/update bower punycode
./vendor/bin/hidev asset-package/update bower adminlte
./vendor/bin/hidev asset-package/update bower autosize
./vendor/bin/hidev asset-package/update bower bootstrap
./vendor/bin/hidev asset-package/update bower bootstrap-daterangepicker
./vendor/bin/hidev asset-package/update bower bootstrap-switch
./vendor/bin/hidev asset-package/update bower chartjs
./vendor/bin/hidev asset-package/update bower drmonty-datatables-plugins
./vendor/bin/hidev asset-package/update bower flag-icon-css
./vendor/bin/hidev asset-package/update bower icheck
./vendor/bin/hidev asset-package/update bower jquery-resizable-columns
./vendor/bin/hidev asset-package/update bower jquery-ui
./vendor/bin/hidev asset-package/update bower less-space
./vendor/bin/hidev asset-package/update bower lightbox2
./vendor/bin/hidev asset-package/update bower matchheight
./vendor/bin/hidev asset-package/update bower moment
./vendor/bin/hidev asset-package/update bower octicons
./vendor/bin/hidev asset-package/update bower paulzi-form
./vendor/bin/hidev asset-package/update bower pnotify
./vendor/bin/hidev asset-package/update bower select2
./vendor/bin/hidev asset-package/update bower store-js
./vendor/bin/hidev asset-package/update bower typeahead.js
./vendor/bin/hidev asset-package/update bower x-editable
